# Generated by Django 5.2 on 2025-04-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_table_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Category',
            new_name='category',
        ),
    ]
